import type { Seniority, Availability, EnglishLevel } from '../src/types'

interface SeedDeveloper {
  name: string
  avatar_initials: string
  location_city: string
  location_country: string
  timezone: string
  utc_offset: number
  role_title: string
  seniority: Seniority
  years_experience: number
  primary_stack: string[]
  secondary_stack: string[]
  specializations: string[]
  hourly_rate_usd: number
  availability: Availability
  weekly_hours: number
  english_level: EnglishLevel
  startup_experience: boolean
  ai_experience: boolean
  bio: string
  is_active: boolean
}

export const SEED_DEVELOPERS: SeedDeveloper[] = [
  // --- LatAm: Brazil -------------------------------------------
  {
    name: 'Lucas Ferreira',
    avatar_initials: 'LF',
    location_city: 'São Paulo',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'Senior Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['React', 'Node.js', 'TypeScript'],
    secondary_stack: ['PostgreSQL', 'Redis', 'Docker'],
    specializations: ['SaaS products', 'startup scaling', 'API design'],
    hourly_rate_usd: 58,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Full-stack engineer with 7 years building SaaS products at Brazilian startups and one YC-backed company. Led a team of 4 engineers shipping a B2B analytics platform from zero to $2M ARR. Strong opinions on clean API design and React architecture.',
    is_active: true,
  },
  {
    name: 'Ana Carolina Souza',
    avatar_initials: 'AS',
    location_city: 'Florianópolis',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'Machine Learning Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['Python', 'PyTorch', 'FastAPI'],
    secondary_stack: ['Kubernetes', 'MLflow', 'PostgreSQL'],
    specializations: ['LLM fine-tuning', 'NLP', 'AI product integration'],
    hourly_rate_usd: 65,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'ML engineer specialized in NLP and LLM applications. Built and deployed fine-tuned models for document classification and extraction at a legal tech startup. Deep experience with the full ML lifecycle from data pipelines to production serving.',
    is_active: true,
  },
  {
    name: 'Rafael Oliveira',
    avatar_initials: 'RO',
    location_city: 'Rio de Janeiro',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'Backend Engineer',
    seniority: 'mid',
    years_experience: 4,
    primary_stack: ['Python', 'Django', 'PostgreSQL'],
    secondary_stack: ['Celery', 'Redis', 'AWS'],
    specializations: ['fintech', 'payment systems', 'data pipelines'],
    hourly_rate_usd: 42,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Backend engineer with 4 years in fintech, building payment processing systems and data pipelines. Solid Django/PostgreSQL experience with a focus on reliability and correctness in financial systems.',
    is_active: true,
  },
  {
    name: 'Mariana Costa',
    avatar_initials: 'MC',
    location_city: 'Belo Horizonte',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'iOS Engineer',
    seniority: 'senior',
    years_experience: 8,
    primary_stack: ['Swift', 'SwiftUI', 'Xcode'],
    secondary_stack: ['Objective-C', 'Firebase', 'REST APIs'],
    specializations: ['consumer apps', 'App Store optimization', 'offline-first architecture'],
    hourly_rate_usd: 60,
    availability: '1_month',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior iOS engineer with 8 years shipping consumer apps. Built and maintained an app with 500K+ MAU for a Brazilian e-commerce company. Expert in SwiftUI and offline-first mobile architecture.',
    is_active: true,
  },
  {
    name: 'Pedro Almeida',
    avatar_initials: 'PA',
    location_city: 'Curitiba',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'DevOps / Platform Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['Kubernetes', 'Terraform', 'AWS'],
    secondary_stack: ['GitHub Actions', 'Datadog', 'Helm'],
    specializations: ['infrastructure scaling', 'CI/CD pipelines', 'cost optimization'],
    hourly_rate_usd: 62,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Platform engineer who scaled infrastructure from 2 to 80 services at a Series B startup. Expert in Kubernetes orchestration and Terraform IaC. Reduced cloud costs by 35% through right-sizing and spot instance strategies.',
    is_active: true,
  },

  // --- LatAm: Argentina ----------------------------------------
  {
    name: 'Valentina García',
    avatar_initials: 'VG',
    location_city: 'Buenos Aires',
    location_country: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    utc_offset: -3,
    role_title: 'Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['React', 'GraphQL', 'Node.js'],
    secondary_stack: ['MongoDB', 'AWS', 'TypeScript'],
    specializations: ['marketplace platforms', 'real-time features', 'startup founding teams'],
    hourly_rate_usd: 55,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'Full-stack engineer with 7 years at Argentine and US-remote startups. Early engineer at a marketplace that sold for $12M. Comfortable being the first or second engineer and making architectural decisions under ambiguity.',
    is_active: true,
  },
  {
    name: 'Mateo Rodríguez',
    avatar_initials: 'MR',
    location_city: 'Córdoba',
    location_country: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    utc_offset: -3,
    role_title: 'Backend Engineer',
    seniority: 'mid',
    years_experience: 3,
    primary_stack: ['Go', 'gRPC', 'PostgreSQL'],
    secondary_stack: ['Docker', 'Kafka', 'Redis'],
    specializations: ['high-throughput APIs', 'microservices', 'event-driven systems'],
    hourly_rate_usd: 38,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: false,
    ai_experience: false,
    bio:
      'Backend engineer specializing in Go and high-throughput distributed systems. Built event-driven microservices handling 50K requests/second. Looking to apply systems expertise in a fast-moving startup environment.',
    is_active: true,
  },
  {
    name: 'Isabella Martínez',
    avatar_initials: 'IM',
    location_city: 'Mendoza',
    location_country: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    utc_offset: -3,
    role_title: 'Staff Frontend Engineer',
    seniority: 'staff',
    years_experience: 10,
    primary_stack: ['React', 'TypeScript', 'Next.js'],
    secondary_stack: ['Storybook', 'Jest', 'Tailwind CSS'],
    specializations: ['design systems', 'frontend architecture', 'performance optimization'],
    hourly_rate_usd: 75,
    availability: '1_month',
    weekly_hours: 40,
    english_level: 'native',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Staff frontend engineer with 10 years building design systems and scalable React architectures. Led frontend at a Series C SaaS company, owned a component library used by 15 engineers. Strong communicator with experience in cross-functional leadership.',
    is_active: true,
  },

  // --- LatAm: Colombia -----------------------------------------
  {
    name: 'Santiago López',
    avatar_initials: 'SL',
    location_city: 'Medellín',
    location_country: 'Colombia',
    timezone: 'America/Bogota',
    utc_offset: -5,
    role_title: 'Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['React', 'Node.js', 'PostgreSQL'],
    secondary_stack: ['TypeScript', 'AWS', 'Prisma'],
    specializations: ['B2B SaaS', 'multi-tenant architecture', 'AI integrations'],
    hourly_rate_usd: 52,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'Full-stack engineer with 6 years building B2B SaaS. Recently integrated OpenAI APIs into a customer support platform, reducing ticket resolution time by 40%. Comfortable owning the entire stack at a small startup.',
    is_active: true,
  },
  {
    name: 'Camila Hernández',
    avatar_initials: 'CH',
    location_city: 'Bogotá',
    location_country: 'Colombia',
    timezone: 'America/Bogota',
    utc_offset: -5,
    role_title: 'Android Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['Kotlin', 'Android', 'Jetpack Compose'],
    secondary_stack: ['Firebase', 'Room', 'REST APIs'],
    specializations: ['fintech mobile apps', 'offline-first', 'biometric auth'],
    hourly_rate_usd: 55,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior Android engineer who shipped the primary banking app for a Colombian neobank with 200K users. Expert in Jetpack Compose and offline-first architecture for unreliable network conditions.',
    is_active: true,
  },
  {
    name: 'Daniel Vargas',
    avatar_initials: 'DV',
    location_city: 'Cali',
    location_country: 'Colombia',
    timezone: 'America/Bogota',
    utc_offset: -5,
    role_title: 'Data Engineer',
    seniority: 'mid',
    years_experience: 4,
    primary_stack: ['Python', 'Airflow', 'Spark'],
    secondary_stack: ['dbt', 'Snowflake', 'BigQuery'],
    specializations: ['data pipelines', 'analytics engineering', 'ELT/ETL'],
    hourly_rate_usd: 44,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Data engineer with 4 years building analytics pipelines for e-commerce and logistics companies. Built a dbt + Airflow pipeline processing 10M daily events for a Colombian logistics startup.',
    is_active: true,
  },

  // --- LatAm: Mexico -------------------------------------------
  {
    name: 'Alejandro Reyes',
    avatar_initials: 'AR',
    location_city: 'Mexico City',
    location_country: 'Mexico',
    timezone: 'America/Mexico_City',
    utc_offset: -6,
    role_title: 'Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 8,
    primary_stack: ['Vue.js', 'Python', 'FastAPI'],
    secondary_stack: ['PostgreSQL', 'Redis', 'Docker'],
    specializations: ['edtech', 'content platforms', 'startup CTO track'],
    hourly_rate_usd: 56,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'Senior engineer with 8 years building edtech platforms and content delivery systems. Was CTO of a 5-person startup for 2 years before joining a larger company. Strong at architectural decisions and mentoring.',
    is_active: true,
  },
  {
    name: 'Sofía Torres',
    avatar_initials: 'ST',
    location_city: 'Guadalajara',
    location_country: 'Mexico',
    timezone: 'America/Mexico_City',
    utc_offset: -6,
    role_title: 'AI/ML Engineer',
    seniority: 'senior',
    years_experience: 5,
    primary_stack: ['Python', 'LangChain', 'OpenAI API'],
    secondary_stack: ['FastAPI', 'Pinecone', 'PostgreSQL'],
    specializations: ['RAG systems', 'LLM applications', 'AI product development'],
    hourly_rate_usd: 68,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'AI engineer focused on LLM applications and RAG systems. Built a legal document analysis tool using GPT-4 and vector search that processes 10K documents/day for a US law firm. Comfortable bridging ML research and production engineering.',
    is_active: true,
  },
  {
    name: 'Carlos Mendoza',
    avatar_initials: 'CM',
    location_city: 'Monterrey',
    location_country: 'Mexico',
    timezone: 'America/Mexico_City',
    utc_offset: -6,
    role_title: 'Backend Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['Java', 'Spring Boot', 'Kafka'],
    secondary_stack: ['PostgreSQL', 'Elasticsearch', 'AWS'],
    specializations: ['enterprise integrations', 'event streaming', 'high availability'],
    hourly_rate_usd: 54,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: false,
    ai_experience: false,
    bio:
      'Backend engineer with 7 years building enterprise-grade Java systems and event streaming platforms. Built Kafka-based integrations for a logistics company processing 5M daily shipment events.',
    is_active: true,
  },

  // --- LatAm: Chile --------------------------------------------
  {
    name: 'Catalina Muñoz',
    avatar_initials: 'CM',
    location_city: 'Santiago',
    location_country: 'Chile',
    timezone: 'America/Santiago',
    utc_offset: -4,
    role_title: 'Full-Stack Engineer',
    seniority: 'mid',
    years_experience: 3,
    primary_stack: ['React', 'TypeScript', 'Node.js'],
    secondary_stack: ['MongoDB', 'GraphQL', 'Vercel'],
    specializations: ['B2C apps', 'rapid prototyping', 'early-stage startups'],
    hourly_rate_usd: 36,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Mid-level full-stack engineer with 3 years at early-stage startups. Shipped 3 different products from zero as the first engineer. Fast learner who thrives in environments with ambiguity and zero legacy code.',
    is_active: true,
  },
  {
    name: 'Felipe Sánchez',
    avatar_initials: 'FS',
    location_city: 'Valparaíso',
    location_country: 'Chile',
    timezone: 'America/Santiago',
    utc_offset: -4,
    role_title: 'Senior React Native Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['React Native', 'TypeScript', 'Expo'],
    secondary_stack: ['Node.js', 'Firebase', 'Redux'],
    specializations: ['cross-platform mobile', 'app store deployment', 'push notifications'],
    hourly_rate_usd: 53,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior React Native engineer with 6 years shipping cross-platform mobile apps. Built a health tracking app reaching 80K downloads in the first month. Expert in Expo ecosystem and app store submission processes.',
    is_active: true,
  },

  // --- LatAm: Peru / Uruguay / Venezuela ----------------------
  {
    name: 'Diego Ramírez',
    avatar_initials: 'DR',
    location_city: 'Lima',
    location_country: 'Peru',
    timezone: 'America/Lima',
    utc_offset: -5,
    role_title: 'Backend Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['Python', 'FastAPI', 'PostgreSQL'],
    secondary_stack: ['AWS Lambda', 'Celery', 'Elasticsearch'],
    specializations: ['e-commerce backends', 'search systems', 'serverless'],
    hourly_rate_usd: 50,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Backend engineer with 6 years building e-commerce and marketplace backends. Built Elasticsearch-powered search and recommendation systems for a Peruvian marketplace with 500K product SKUs.',
    is_active: true,
  },
  {
    name: 'Nicolás Castro',
    avatar_initials: 'NC',
    location_city: 'Montevideo',
    location_country: 'Uruguay',
    timezone: 'America/Montevideo',
    utc_offset: -3,
    role_title: 'Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 9,
    primary_stack: ['React', 'Ruby on Rails', 'PostgreSQL'],
    secondary_stack: ['TypeScript', 'Redis', 'Heroku'],
    specializations: ['SaaS architecture', 'multi-tenant', 'team leadership'],
    hourly_rate_usd: 60,
    availability: '1_month',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior full-stack engineer with 9 years at SaaS companies. Has worked US-remote since 2018. Led a 3-person team rewriting a Rails monolith into a multi-tenant SaaS platform that grew from $500K to $3M ARR.',
    is_active: true,
  },
  {
    name: 'Andrea Blanco',
    avatar_initials: 'AB',
    location_city: 'Caracas',
    location_country: 'Venezuela',
    timezone: 'America/Caracas',
    utc_offset: -4,
    role_title: 'Frontend Engineer',
    seniority: 'mid',
    years_experience: 4,
    primary_stack: ['React', 'TypeScript', 'Tailwind CSS'],
    secondary_stack: ['Next.js', 'Storybook', 'Figma'],
    specializations: ['UI engineering', 'pixel-perfect implementation', 'component libraries'],
    hourly_rate_usd: 38,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Frontend engineer with 4 years translating Figma designs into production-ready React. Strong collaboration with designers and product managers. Built a component library of 60+ components for a healthcare startup.',
    is_active: true,
  },

  // --- MENA / Eastern Europe (DevSignal is expanding here) ----
  {
    name: 'Omar Al-Hassan',
    avatar_initials: 'OH',
    location_city: 'Amman',
    location_country: 'Jordan',
    timezone: 'Asia/Amman',
    utc_offset: 3,
    role_title: 'Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['React', 'Node.js', 'TypeScript'],
    secondary_stack: ['PostgreSQL', 'Docker', 'Azure'],
    specializations: ['fintech', 'Arabic-language products', 'MENA market'],
    hourly_rate_usd: 48,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Full-stack engineer with 7 years at Jordanian and UAE-based fintech startups. Built a BNPL product from scratch for the MENA market. Experienced working with US-based founding teams across time zones.',
    is_active: true,
  },
  {
    name: 'Youssef Khalil',
    avatar_initials: 'YK',
    location_city: 'Cairo',
    location_country: 'Egypt',
    timezone: 'Africa/Cairo',
    utc_offset: 2,
    role_title: 'Backend Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['Python', 'Django', 'PostgreSQL'],
    secondary_stack: ['Celery', 'Redis', 'AWS'],
    specializations: ['logistics tech', 'API design', 'backend scalability'],
    hourly_rate_usd: 40,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior backend engineer with 6 years building Django-based logistics and supply chain platforms. Part of the founding engineering team at an Egyptian logistics startup that scaled to 50 cities.',
    is_active: true,
  },
  {
    name: 'Lena Kovacevic',
    avatar_initials: 'LK',
    location_city: 'Belgrade',
    location_country: 'Serbia',
    timezone: 'Europe/Belgrade',
    utc_offset: 1,
    role_title: 'Senior Full-Stack Engineer',
    seniority: 'senior',
    years_experience: 8,
    primary_stack: ['React', '.NET', 'C#'],
    secondary_stack: ['Azure', 'PostgreSQL', 'TypeScript'],
    specializations: ['enterprise SaaS', 'B2B platforms', 'EU compliance'],
    hourly_rate_usd: 52,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: false,
    ai_experience: false,
    bio:
      'Senior full-stack engineer with 8 years building enterprise SaaS on .NET and React. Strong in GDPR compliance, authentication systems, and Azure deployments. Looking to move from enterprise to a growth-stage startup.',
    is_active: true,
  },
  {
    name: 'Andrei Popescu',
    avatar_initials: 'AP',
    location_city: 'Bucharest',
    location_country: 'Romania',
    timezone: 'Europe/Bucharest',
    utc_offset: 2,
    role_title: 'Principal Backend Engineer',
    seniority: 'principal',
    years_experience: 12,
    primary_stack: ['Rust', 'Go', 'PostgreSQL'],
    secondary_stack: ['Kubernetes', 'Kafka', 'gRPC'],
    specializations: ['systems programming', 'performance engineering', 'technical strategy'],
    hourly_rate_usd: 90,
    availability: '1_month',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Principal engineer with 12 years in systems and infrastructure. Designed the core data streaming architecture for a Series C fintech processing $2B in annual transactions. Looking to join a technically ambitious team as an early high-impact hire.',
    is_active: true,
  },

  // --- Additional LatAm specialists ---------------------------
  {
    name: 'Juliana Nunes',
    avatar_initials: 'JN',
    location_city: 'Porto Alegre',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'AI Integration Engineer',
    seniority: 'mid',
    years_experience: 3,
    primary_stack: ['Python', 'OpenAI API', 'LangChain'],
    secondary_stack: ['FastAPI', 'PostgreSQL', 'Next.js'],
    specializations: ['AI product development', 'prompt engineering', 'RAG pipelines'],
    hourly_rate_usd: 44,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'AI integration engineer who has spent the last 2 years building LLM-powered products from prototypes to production. Built a RAG-based knowledge base product for a Brazilian HR software company with 3K business customers.',
    is_active: true,
  },
  {
    name: 'Tomás Gutiérrez',
    avatar_initials: 'TG',
    location_city: 'Bogotá',
    location_country: 'Colombia',
    timezone: 'America/Bogota',
    utc_offset: -5,
    role_title: 'Senior React / Next.js Engineer',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['React', 'Next.js', 'TypeScript'],
    secondary_stack: ['tRPC', 'Prisma', 'Vercel'],
    specializations: ['frontend performance', 'SEO', 'e-commerce storefronts'],
    hourly_rate_usd: 50,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior Next.js specialist with 6 years focused on frontend performance and SEO. Rebuilt a Colombian e-commerce storefront in Next.js, improving Core Web Vitals scores and increasing organic traffic by 60%.',
    is_active: true,
  },
  {
    name: 'Renata Lima',
    avatar_initials: 'RL',
    location_city: 'Recife',
    location_country: 'Brazil',
    timezone: 'America/Recife',
    utc_offset: -3,
    role_title: 'Security Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['Python', 'AWS Security', 'Node.js'],
    secondary_stack: ['Terraform', 'SAST tools', 'Burp Suite'],
    specializations: ['AppSec', 'pentesting', 'SOC 2 compliance', 'security automation'],
    hourly_rate_usd: 64,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Application security engineer with 7 years helping startups build secure-by-default systems. Led SOC 2 Type II certification for two SaaS companies. Expert in threat modeling and security automation.',
    is_active: true,
  },
  {
    name: 'Gabriel Santos',
    avatar_initials: 'GS',
    location_city: 'Salvador',
    location_country: 'Brazil',
    timezone: 'America/Bahia',
    utc_offset: -3,
    role_title: 'Full-Stack Engineer',
    seniority: 'junior',
    years_experience: 1,
    primary_stack: ['React', 'Node.js', 'PostgreSQL'],
    secondary_stack: ['TypeScript', 'Tailwind CSS'],
    specializations: ['rapid prototyping', 'strong fundamentals'],
    hourly_rate_usd: 24,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: false,
    ai_experience: false,
    bio:
      'Junior full-stack engineer with 1 year of professional experience after an intensive bootcamp. Built two side projects with real users. Fast learner looking for a startup where they can grow quickly.',
    is_active: true,
  },
  {
    name: 'Elena Vásquez',
    avatar_initials: 'EV',
    location_city: 'Buenos Aires',
    location_country: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    utc_offset: -3,
    role_title: 'Product Engineer',
    seniority: 'senior',
    years_experience: 7,
    primary_stack: ['React', 'Ruby on Rails', 'PostgreSQL'],
    secondary_stack: ['Stripe', 'Intercom', 'TypeScript'],
    specializations: ['product-led growth', 'billing systems', 'onboarding flows'],
    hourly_rate_usd: 58,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Product engineer who thinks like a founder. Has owned onboarding, activation, and monetization features end-to-end at two B2B SaaS companies. Loves working on problems that directly tie to ARR.',
    is_active: true,
  },
  {
    name: 'Paulo Carvalho',
    avatar_initials: 'PC',
    location_city: 'São Paulo',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'Staff Backend Engineer',
    seniority: 'staff',
    years_experience: 11,
    primary_stack: ['Go', 'Python', 'PostgreSQL'],
    secondary_stack: ['Kafka', 'Kubernetes', 'AWS'],
    specializations: ['platform engineering', 'developer tooling', 'technical strategy'],
    hourly_rate_usd: 80,
    availability: '1_month',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Staff engineer with 11 years, most recently leading platform engineering at a Brazilian fintech with 200 engineers. Expert at building internal developer platforms and defining engineering standards that scale.',
    is_active: true,
  },
  {
    name: 'Jorge Espinosa',
    avatar_initials: 'JE',
    location_city: 'Mexico City',
    location_country: 'Mexico',
    timezone: 'America/Mexico_City',
    utc_offset: -6,
    role_title: 'Senior Mobile Engineer (React Native)',
    seniority: 'senior',
    years_experience: 5,
    primary_stack: ['React Native', 'TypeScript', 'Expo'],
    secondary_stack: ['GraphQL', 'Firebase', 'Redux Toolkit'],
    specializations: ['fintech mobile', 'biometric authentication', 'real-time updates'],
    hourly_rate_usd: 52,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Senior React Native engineer with 5 years building fintech and payments mobile apps. Built real-time crypto trading mobile interfaces and biometric auth flows. Comfortable handling App Store and Play Store deployment.',
    is_active: true,
  },
  {
    name: 'Bianca Fonseca',
    avatar_initials: 'BF',
    location_city: 'Rio de Janeiro',
    location_country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    utc_offset: -3,
    role_title: 'Senior Data Scientist',
    seniority: 'senior',
    years_experience: 6,
    primary_stack: ['Python', 'scikit-learn', 'SQL'],
    secondary_stack: ['dbt', 'Airflow', 'Tableau'],
    specializations: ['recommendation systems', 'churn prediction', 'A/B testing'],
    hourly_rate_usd: 62,
    availability: '2_weeks',
    weekly_hours: 40,
    english_level: 'fluent',
    startup_experience: true,
    ai_experience: true,
    bio:
      'Senior data scientist with 6 years in e-commerce and marketplace analytics. Built recommendation systems that increased GMV by 18% at a Brazilian marketplace. Bridges the gap between data science and product decisions.',
    is_active: true,
  },
  {
    name: 'Ricardo Herrera',
    avatar_initials: 'RH',
    location_city: 'Medellín',
    location_country: 'Colombia',
    timezone: 'America/Bogota',
    utc_offset: -5,
    role_title: 'Full-Stack Engineer',
    seniority: 'mid',
    years_experience: 4,
    primary_stack: ['Vue.js', 'Laravel', 'MySQL'],
    secondary_stack: ['Docker', 'AWS', 'Redis'],
    specializations: ['healthtech', 'B2B SaaS', 'clinical workflows'],
    hourly_rate_usd: 40,
    availability: 'immediate',
    weekly_hours: 40,
    english_level: 'conversational',
    startup_experience: true,
    ai_experience: false,
    bio:
      'Full-stack engineer with 4 years in healthtech, building clinical workflow tools for Colombian hospitals. Deep domain knowledge in healthcare data standards and patient management systems.',
    is_active: true,
  },
]